# Basic Information 
title: "Dr. Lucas Corrêa Lopes"
position: Postdoctoral Researcher
affiliation: Federal University of Minas Gerais
email: lucasclopes@ufmg.br

# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
keywords: Lucas Corrêa Lopes, Lucas Lopes, Profinite groups, profinite trees, acylindrical actions, Bass-Serre theory, UnB, UFMG
description: Official page of Lucas Corrêa Lopes. Postdoctoral researcher at UFMG. Includes the doctoral thesis "Profinite groups acting acylindrically on profinite trees" and research on profinite group theory.
canonical: https://lcorrealopes.github.io/home/

# Links 
# If you don't need one of them, you may delete the corresponding line.
cv_link: /assets/files/CV.pdf
twitter: https://twitter.com/mestre_lc

# Images (e.g., your profile picture and your website's favicon) 
# "favicon" and "favicon_dark" are used for the light and dark modes, respectively. 
avatar: ./assets/img/newprofilepic.jpg
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# Footnote
# You may use the option to disable the footnote, "Powered by Jekyll and Minimal Light theme."
enable_footnote: false

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Use this project as a remote theme for GitHub Pages
# See the guide here: https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll
remote_theme: yaoyao-liu/minimal-light

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
